version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - sqlite_data:/app/prisma
    environment:
      - NODE_ENV=development
    command: sh -c "npx prisma migrate dev && npx prisma db seed && npm run dev"

volumes:
  sqlite_data: 